<#
.DESCRIPTION
    SENDS THE KEYSTROKE SHIFT + F15 EVERY 60 SECONDS INDEFINITELY.
    COMPUTER WILL NEVER GO TO SLEEP. SCREEN WILL NEVER LOCK & SCREENSAVER WILL NEVER APPEAR.
    THIS SCRIPT WILL KEEP YOUR SYSTEM AWAKE AND COMBAT INACTIVITY/ TIMEOUT POLICIES
.AUTHOR
    TYLER NEELY
.CREATED
    6/15/2022
#>

$wsh = New-Object -ComObject WScript.Shell
while (1) {   
  $wsh.SendKeys('+{F15}')
  Start-Sleep -seconds 59
  }
